#jms_security_extra:
#    secure_all_services: false
#    expressions: true

security:
    encoders:
        BddSBP\ReaderBundle\Entity\Reader: { algorithm: sha512, iterations: 10 }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        readers: 
          entity: { class: BddSBP\ReaderBundle\Entity\Reader, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
       
        secured_area:
            pattern:    ^/
            provider:   readers
            anonymous: ~
            form_login:
                login_path:  reader_login
                check_path:  reader_login_check
                success_handler: reader.security.login_handler
            logout:
                path:   /logout
                target: / 
                # for php 5.4.9 the problem with Logout action: SessionHandler::write():
                # Parent session handler is not open fix in php 5.4.11
                invalidate_session: false
                
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
